server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/voting_db
spring.datasource.username=root
spring.datasource.password=Babulkumar@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=verysecretkey123456
vote.encryption.secret=0123456789abcdef
vote.encryption.iv=fedcba9876543210
